language: node_js
node_js: 8

sudo: required
services:
  - docker

before_install:
  - docker build -t sauliusonis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sauliusonis/react-test npm test


after_success:
  - docker build -t sauliusonis/multi-client ./client
  - docker build -t sauliusonis/multi-nginx ./nginx
  - docker build -t sauliusonis/multi-server ./server
  - docker build -t sauliusonis/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sauliusonis/multi-client
  - docker push sauliusonis/multi-nginx
  - docker push sauliusonis/multi-server
  - docker push sauliusonis/multi-worker